name: aws-actions-sample

permissions:
  id-token: write
  contents: read
  actions: read

on:
  workflow_dispatch:

jobs:
  test:
    name: aws test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::943485981463:role/dmt-github-actions-cd-role
        aws-region: ap-northeast-1

    - name: s3 list
      run: |
        aws s3 ls

