name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:  
        - dev
        - prod
        description: '環境'

jobs:
  call-workflow:
    # {owner}・{repo}・{path}・{ref}はReusable Workflowを定義しているリポジトリに読み替え
    uses: {owner}/{repo}/{path}@{ref}
    with:
      env: ${{ github.event.inputs.env }}
      command: s3 ls
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

