name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options:  
        - dev
        - prod
        description: '環境'

jobs:
  call-workflow:
    # {owner}・{repo}・{path}・{ref}はReusable Workflowを定義しているリポジトリに読み替え
    uses: yasuhiko-inoue-stb/github-actions-sample/.github/workflows/reusable-workflow.yml@main
    with:
      env: ${{ github.event.inputs.env }}
      command: s3 ls
    secrets:
      access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

