name: composite-action-sample
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Initialize
      # {owner}と{repo}にはComposite Action用のリポジトリを指定
      uses: yasuhiko-inoue-stb/github-composite-actions-sample/composite-action/init@main
      with:
        node-version: 16.x
