name: Reusable workflow example

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      env:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  example_job:
    environment: ${{ inputs.env }}
    name: exec aws command
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: aws ${{ inputs.command }}
        run: |
          aws ${{ inputs.command }} 

