name: Reusable workflow example

on:
  # Reusable Workflowはworkflow_call
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      env:
        required: true
        type: string
    # 呼び出し側より取得するsecretを指定
    secrets:
      access_key_id:
        required: true
      secret_access_key:
        required: true

jobs:
  example_job:
    # Environment Secretを使う場合はReusable Workflow側で設定
    environment: ${{ inputs.env }}
    name: exec aws command
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.access_key_id }}
          aws-secret-access-key: ${{ secrets.secret_access_key }}
          aws-region: ap-northeast-1

      - name: aws ${{ inputs.command }}
        run: |
          aws ${{ inputs.command }}

